-- Insert test data for development and testing
INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('john.doe', toDate(now()) - 1, 'BP-12345', 15234, 87.3, 145.2, 52.1, 85.2, 72.0, 3, 12.5, 'John Doe', 'john@example.com', 'BionicArm Pro X1', '2024-06-15');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('john.doe', toDate(now()) - 2, 'BP-12345', 14892, 89.1, 158.3, 48.9, 82.1, 68.0, 5, 11.8, 'John Doe', 'john@example.com', 'BionicArm Pro X1', '2024-06-15');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('john.doe', toDate(now()) - 3, 'BP-12345', 16123, 85.7, 142.1, 51.3, 88.5, 75.0, 2, 13.2, 'John Doe', 'john@example.com', 'BionicArm Pro X1', '2024-06-15');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('jane.smith', toDate(now()) - 1, 'BP-23456', 13567, 92.4, 165.7, 55.2, 79.3, 65.0, 4, 10.3, 'Jane Smith', 'jane@example.com', 'BionicHand Elite', '2024-07-20');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('jane.smith', toDate(now()) - 2, 'BP-23456', 14231, 90.8, 171.2, 53.8, 81.7, 69.0, 3, 11.1, 'Jane Smith', 'jane@example.com', 'BionicHand Elite', '2024-07-20');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('alex.johnson', toDate(now()) - 1, 'BP-34567', 17894, 83.2, 138.9, 49.7, 91.2, 80.0, 1, 14.7, 'Alex Johnson', 'alex@example.com', 'BionicArm Pro X2', '2024-08-10');

INSERT INTO bionicpro.user_reports (user_id, report_date, prosthesis_id, total_movements, avg_response_time_ms, max_response_time_ms, min_response_time_ms, battery_avg_percent, battery_min_percent, error_count, total_usage_hours, customer_name, customer_email, prosthesis_model, prosthesis_manufacture_date) VALUES ('alex.johnson', toDate(now()) - 2, 'BP-34567', 17123, 84.5, 142.3, 50.1, 89.8, 78.0, 2, 14.2, 'Alex Johnson', 'alex@example.com', 'BionicArm Pro X2', '2024-08-10');
